import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, ExternalLink, Pencil, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/app/AppShell";
import { DeadlineBadge, PriorityBadge, ReadinessProgress, StatusBadge } from "@/components/app/Badges";
import { ConfirmationDialog } from "@/components/app/ConfirmationDialog";
import { ProgramForm } from "@/components/app/ProgramForm";
import { RequirementChecklist } from "@/components/app/RequirementChecklist";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { usePrograms,useRequirements,useDocuments,useRecommendationRequests,useRecommenders,useDeleteRow,useSaveRow,readiness,requirementsFor,documentFileUrl } from "@/lib/data";
import { formatDate,formatMoney } from "@/lib/format";
import { pageMeta } from "@/lib/page-meta";
import { toast } from "sonner";
export const Route=createFileRoute("/_authenticated/programs/$programId")({head:()=>pageMeta("Program details","Review an application's readiness, requirements, documents, recommendations, and notes."),component:ProgramDetail});
function ProgramDetail(){
 const {user}=Route.useRouteContext(); const {programId}=Route.useParams(); const navigate=useNavigate(); const {data:programs=[],isLoading,isError}=usePrograms(); const {data:allRequirements=[]}=useRequirements(); const {data:documents=[]}=useDocuments(); const {data:requests=[]}=useRecommendationRequests(); const {data:recommenders=[]}=useRecommenders(); const remove=useDeleteRow("programs","Program"), save=useSaveRow("programs","Program"); const [edit,setEdit]=useState(false),[notes,setNotes]=useState(""); const program=programs.find(p=>p.id===programId); useEffect(()=>setNotes(program?.notes??""),[program?.id,program?.notes]);
 if(isLoading)return <AppShell title="Program" email={user.email}><p>Loading program…</p></AppShell>;
 if(isError||!program)return <AppShell title="Program" email={user.email}><p className="text-destructive">{isError?"Could not load program.":"Program not found."}</p><Button asChild variant="outline" className="mt-4"><Link to="/programs">Back to programs</Link></Button></AppShell>;
 const reqs=requirementsFor(allRequirements,programId); const linkedIds=new Set(reqs.map(r=>r.document_id).filter(Boolean)); const linked=documents.filter(d=>linkedIds.has(d.id)); const relatedRequests=requests.filter(r=>r.program_id===programId);
 const link=(url:string|null,label:string)=>url?<Button asChild variant="outline" size="sm"><a href={url} target="_blank" rel="noopener noreferrer">{label}<ExternalLink className="size-3"/></a></Button>:null;
 const fact=(label:string,value:string|number|null|undefined)=><div className="border-b border-border py-3"><dt className="text-xs font-medium text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-medium">{value||"—"}</dd></div>;
 async function deleteProgram(){try{await remove.mutateAsync(programId);navigate({to:"/programs"})}catch{}}
 return <AppShell title={program.university} subtitle={`${program.program_name} · ${[program.country,program.city].filter(Boolean).join(" · ")}`} email={user.email} actions={<Button size="icon" variant="outline" aria-label="Edit program" onClick={()=>setEdit(true)}><Pencil className="size-4"/></Button>}>
 <Link to="/programs" className="mb-5 inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="size-4"/> Programs</Link>
 <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="font-display text-xl font-semibold text-primary">{program.program_name}</p><p className="mt-1 text-sm text-muted-foreground">{program.major||"Major not set"}</p><div className="mt-3 flex flex-wrap gap-2"><StatusBadge status={program.status}/><PriorityBadge priority={program.priority}/></div></div><div className="flex flex-wrap gap-2">{link(program.program_link,"Program website")}{link(program.scholarship_link,"Scholarship")}{link(program.application_link,"Application portal")}</div></div>
 <div className="mb-8 grid gap-4 md:grid-cols-2"><div className="rounded-lg border bg-surface p-5"><p className="text-xs font-semibold uppercase text-muted-foreground">Application deadline</p><p className="mt-2 font-display text-xl text-primary">{formatDate(program.deadline)}</p><DeadlineBadge date={program.deadline} className="mt-2"/></div><div className="rounded-lg border bg-surface p-5"><p className="mb-3 text-xs font-semibold uppercase text-muted-foreground">Application readiness</p><ReadinessProgress value={readiness(reqs)}/><p className="mt-3 text-xs text-muted-foreground">{reqs.filter(r=>r.is_required&&r.status==="Completed").length} of {reqs.filter(r=>r.is_required&&r.status!=="Not Required").length} required items complete</p></div></div>
 <Tabs defaultValue="overview"><TabsList className="mb-5 flex h-auto flex-wrap justify-start gap-1 bg-transparent p-0">{["Overview","Requirements","Documents","Recommendations","Notes"].map(t=><TabsTrigger key={t} value={t.toLowerCase()}>{t}</TabsTrigger>)}</TabsList>
 <TabsContent value="overview"><dl className="grid gap-x-8 sm:grid-cols-2 lg:grid-cols-3">{fact("Degree",program.degree_type)}{fact("Major",program.major)}{fact("Research topic",program.research_topic)}{fact("Scholarship",program.scholarship_name)}{fact("Funding",program.funding_type)}{fact("Tuition fee",formatMoney(program.tuition_fee))}{fact("Application fee",formatMoney(program.application_fee))}{fact("Scholarship deadline",formatDate(program.scholarship_deadline))}{fact("Status",program.status)}{fact("Priority",program.priority)}</dl><ConfirmationDialog trigger={<Button variant="outline" className="mt-8 text-destructive"><Trash2 className="size-4"/> Delete program</Button>} title="Delete this program?" description="The program and its requirements and recommendations will be permanently removed." onConfirm={()=>void deleteProgram()}/></TabsContent>
 <TabsContent value="requirements"><RequirementChecklist programId={programId} requirements={reqs} documents={documents}/></TabsContent>
 <TabsContent value="documents"><div className="space-y-3">{linked.length?linked.map(d=><div key={d.id} className="flex items-center justify-between border-b py-3"><div><p className="font-medium">{d.name}</p><p className="text-xs text-muted-foreground">{d.document_type} · {d.version||"No version"} · {d.status}</p></div>{d.file_url&&<Button variant="outline" size="sm" onClick={async()=>{try{window.open(await documentFileUrl(d.file_url as string),"_blank","noopener,noreferrer")}catch{toast.error("Could not open file")}}}>Open file</Button>}</div>):<p className="text-sm text-muted-foreground">No documents linked to requirements yet.</p>}<p className="text-xs text-muted-foreground">Link documents in the Requirements tab, or add them to your <Link to="/documents" className="text-primary underline">library</Link>.</p></div></TabsContent>
 <TabsContent value="recommendations"><div className="space-y-3">{relatedRequests.length?relatedRequests.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 border-b py-3"><div><p className="font-medium">{recommenders.find(rec=>rec.id===r.recommender_id)?.name??"Recommender"}</p><p className="text-xs text-muted-foreground">Requested {formatDate(r.requested_date)} · Received {formatDate(r.received_date)} · Deadline {formatDate(r.deadline)}</p></div><StatusBadge status={r.status}/></div>):<p className="text-sm text-muted-foreground">No recommendation requests for this program.</p>}<Button asChild variant="outline" size="sm"><Link to="/recommendations">Manage recommendations</Link></Button></div></TabsContent>
 <TabsContent value="notes"><div className="max-w-2xl space-y-3"><Textarea aria-label="Program notes" rows={10} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Add your notes…"/><Button disabled={save.isPending||notes===(program.notes??"")} onClick={async()=>{try{await save.mutateAsync({id:program.id,notes:notes.trim()||null})}catch{}}}>Save notes</Button></div></TabsContent></Tabs>
 <ProgramForm key={edit?program.id:"closed"} open={edit} onOpenChange={setEdit} program={program}/></AppShell>;
}
