import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { LayoutGrid, List, Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { AppShell } from "@/components/app/AppShell";
import { ProgramCard } from "@/components/app/ProgramCard";
import { ProgramTable } from "@/components/app/ProgramTable";
import { ProgramForm } from "@/components/app/ProgramForm";
import { EmptyState } from "@/components/app/EmptyState";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { usePrograms,useRequirements,readiness,requirementsFor } from "@/lib/data";
import { PROGRAM_STATUSES,PRIORITIES } from "@/lib/constants";
import { pageMeta } from "@/lib/page-meta";
export const Route = createFileRoute("/_authenticated/programs/")({head:()=>pageMeta("Programs","Search, compare, and track master's degree and scholarship applications."),component:ProgramsPage});
function ProgramsPage(){
 const {user}=Route.useRouteContext(); const navigate=useNavigate(); const {data:programs=[],isLoading,isError}=usePrograms(); const {data:requirements=[]}=useRequirements();
 const [open,setOpen]=useState(false),[query,setQuery]=useState(""),[country,setCountry]=useState("all"),[major,setMajor]=useState("all"),[status,setStatus]=useState("all"),[priority,setPriority]=useState("all"),[deadline,setDeadline]=useState("all"),[sort,setSort]=useState("deadline"),[scholarship,setScholarship]=useState(false),[view,setView]=useState<"cards"|"table">("cards");
 const filtered=useMemo(()=>programs.filter(p=>[p.university,p.program_name,p.scholarship_name,p.country,p.major,p.research_topic].some(s=>s?.toLowerCase().includes(query.toLowerCase())) && (country==="all"||p.country===country) && (major==="all"||p.major===major) && (status==="all"||p.status===status) && (priority==="all"||p.priority===priority) && (!scholarship||!!p.scholarship_name) && (deadline==="all" || (deadline==="upcoming" ? !!p.deadline&&p.deadline>=new Date().toISOString().slice(0,10) : deadline==="overdue" ? !!p.deadline&&p.deadline<new Date().toISOString().slice(0,10) : !p.deadline))).sort((a,b)=>sort==="priority" ? (["High","Medium","Low"].indexOf(a.priority)-["High","Medium","Low"].indexOf(b.priority)) : (a.deadline??"9999").localeCompare(b.deadline??"9999")),[programs,query,country,major,status,priority,scholarship,deadline,sort]);
 const readinessById=Object.fromEntries(filtered.map(p=>[p.id,readiness(requirementsFor(requirements,p.id))]));
 const select=(label:string,value:string,change:(v:string)=>void,options:string[]) => <Select value={value} onValueChange={change}><SelectTrigger aria-label={label} className="w-full sm:w-40"><SelectValue placeholder={label}/></SelectTrigger><SelectContent><SelectItem value="all">All {label.toLowerCase()}</SelectItem>{options.filter(Boolean).map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>;
 return <AppShell title="Programs" subtitle={`${programs.length} applications in your workspace`} email={user.email} actions={<Button size="sm" onClick={()=>setOpen(true)}><Plus className="size-4"/> Add program</Button>}>
 <div className="mb-5 space-y-3"><div className="flex flex-wrap gap-2"><div className="relative min-w-48 flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input aria-label="Search programs" placeholder="Search programs, universities…" className="pl-9" value={query} onChange={e=>setQuery(e.target.value)}/></div>{select("Country",country,setCountry,[...new Set(programs.map(p=>p.country))])}{select("Major",major,setMajor,[...new Set(programs.map(p=>p.major))])}{select("Status",status,setStatus,[...PROGRAM_STATUSES])}{select("Priority",priority,setPriority,[...PRIORITIES])}</div><div className="flex flex-wrap items-center gap-3">{select("Deadline",deadline,setDeadline,["upcoming","overdue","none"])}<Select value={sort} onValueChange={setSort}><SelectTrigger aria-label="Sort programs" className="w-40"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="deadline">Sort: deadline</SelectItem><SelectItem value="priority">Sort: priority</SelectItem></SelectContent></Select><label className="flex items-center gap-2 text-sm"><Checkbox checked={scholarship} onCheckedChange={v=>setScholarship(v===true)}/> Scholarships only</label><div className="ml-auto hidden gap-1 md:flex"><Button size="icon" variant={view==="cards"?"secondary":"ghost"} aria-label="Card view" onClick={()=>setView("cards")}><LayoutGrid className="size-4"/></Button><Button size="icon" variant={view==="table"?"secondary":"ghost"} aria-label="Table view" onClick={()=>setView("table")}><List className="size-4"/></Button></div></div></div>
 {isLoading?<p className="text-muted-foreground">Loading programs…</p>:isError?<p role="alert" className="text-destructive">Could not load programs.</p>:filtered.length===0?<EmptyState title={programs.length?"No matching programs":"No programs yet"} description={programs.length?"Try changing your search or filters.":"Add a program to start tracking your applications."} action={!programs.length?<Button onClick={()=>setOpen(true)}>Add program</Button>:undefined}/>:view==="table"?<ProgramTable programs={filtered} readinessById={readinessById}/>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(p=><ProgramCard key={p.id} program={p} readinessValue={readinessById[p.id]??0}/>)}</div>}
 <ProgramForm key={open?"new":"closed"} open={open} onOpenChange={setOpen} onSaved={id=>navigate({to:"/programs/$programId",params:{programId:id}})}/></AppShell>;
}
