import { createFileRoute,Link } from "@tanstack/react-router";
import { ChevronLeft,ChevronRight,Plus,Pencil,Trash2 } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/app/AppShell";
import { ConfirmationDialog } from "@/components/app/ConfirmationDialog";
import { Field,FormModal } from "@/components/app/FormModal";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { EVENT_TYPES } from "@/lib/constants";
import { usePrograms,useEvents,useRecommendationRequests,useRequirements,useLanguageTests,useSaveRow,useDeleteRow,type ApplicationEvent } from "@/lib/data";
import { formatDate,todayISO } from "@/lib/format";
import { pageMeta } from "@/lib/page-meta";
export const Route=createFileRoute("/_authenticated/calendar")({head:()=>pageMeta("Calendar","See application deadlines, scholarship dates, tests, and tasks on one calendar."),component:CalendarPage});
type Entry={id:string,date:string,title:string,type:string,programId?:string,source?:ApplicationEvent};
const EMPTY={title:"",date:todayISO(),event_type:"Other",program_id:"none",notes:"",completed:false};
function CalendarPage(){const {user}=Route.useRouteContext();const {data:programs=[]}=usePrograms(),{data:events=[],isLoading,isError}=useEvents(),{data:requests=[]}=useRecommendationRequests(),{data:requirements=[]}=useRequirements(),{data:tests=[]}=useLanguageTests();const save=useSaveRow("application_events","Event"),remove=useDeleteRow("application_events","Event");const [month,setMonth]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)}),[selected,setSelected]=useState(todayISO()),[open,setOpen]=useState(false),[editing,setEditing]=useState<ApplicationEvent|null>(null),[draft,setDraft]=useState(EMPTY);
 const entries:Entry[]=[...programs.flatMap(p=>[{id:`a-${p.id}`,date:p.deadline,title:`${p.university} · Application`,type:"Application Deadline",programId:p.id},{id:`s-${p.id}`,date:p.scholarship_deadline,title:`${p.university} · Scholarship`,type:"Scholarship Deadline",programId:p.id}].flatMap(e=>e.date?[{...e,date:e.date}]:[])),...events.map(e=>({id:e.id,date:e.date,title:e.title,type:e.event_type,programId:e.program_id??undefined,source:e})),...requests.filter(r=>!!r.deadline).map(r=>({id:`r-${r.id}`,date:r.deadline as string,title:`${programs.find(p=>p.id===r.program_id)?.university??"Program"} · Letter`,type:"Recommendation",programId:r.program_id})),...requirements.filter(r=>!!r.deadline).map(r=>({id:`q-${r.id}`,date:r.deadline as string,title:r.name,type:"Document",programId:r.program_id})),...tests.filter(t=>!!t.test_date).map(t=>({id:`t-${t.id}`,date:t.test_date as string,title:t.test_type,type:"Language Test"}))];
 const start=new Date(month.getFullYear(),month.getMonth(),1).getDay(),days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();const cells=Array.from({length:Math.ceil((start+days)/7)*7},(_,i)=>{const day=i-start+1;return day>0&&day<=days?day:null});const dateFor=(day:number)=>`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`;const selectedEntries=entries.filter(e=>e.date===selected);const tone=(type:string)=>type==="Application Deadline"?"bg-primary/10 text-primary":type==="Scholarship Deadline"?"bg-plum/15 text-plum":type==="Recommendation"?"bg-blush/45 text-blush-foreground":type==="Language Test"?"bg-success/15 text-success":"bg-secondary text-secondary-foreground";
 function show(e?:ApplicationEvent){setEditing(e??null);setDraft(e?{title:e.title,date:e.date,event_type:e.event_type,program_id:e.program_id??"none",notes:e.notes??"",completed:e.completed}:{...EMPTY,date:selected});setOpen(true)}
 async function submit(ev:React.FormEvent){ev.preventDefault();try{await save.mutateAsync({...draft,title:draft.title.trim(),program_id:draft.program_id==="none"?null:draft.program_id,notes:draft.notes||null,...(editing?{id:editing.id}:{})});setOpen(false)}catch{}}
 return <AppShell title="Calendar" subtitle="A clear view of every important date" email={user.email} actions={<Button size="sm" onClick={()=>show()}><Plus className="size-4"/> Add event</Button>}><div className="mb-5 flex items-center gap-2"><Button variant="outline" size="icon" aria-label="Previous month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft className="size-4"/></Button><h2 className="min-w-40 text-center text-xl">{month.toLocaleDateString("en-GB",{month:"long",year:"numeric"})}</h2><Button variant="outline" size="icon" aria-label="Next month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight className="size-4"/></Button><Button variant="ghost" size="sm" onClick={()=>{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1));setSelected(todayISO())}}>Today</Button></div>
 {isLoading?<p>Loading calendar…</p>:isError?<p role="alert" className="text-destructive">Could not load events.</p>:<div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_280px]"><div className="overflow-hidden rounded-lg border bg-surface"><div className="grid grid-cols-7 border-b bg-secondary/50 text-center text-xs font-semibold text-muted-foreground">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><span key={d} className="py-3">{d}</span>)}</div><div className="grid grid-cols-7">{cells.map((day,index)=>day?<button key={index} type="button" onClick={()=>setSelected(dateFor(day))} aria-label={formatDate(dateFor(day))} aria-pressed={selected===dateFor(day)} className={`min-h-20 border-b border-r p-1 text-left align-top transition-colors hover:bg-accent sm:min-h-28 sm:p-2 ${selected===dateFor(day)?"bg-accent":""}`}><span className={`inline-flex size-6 items-center justify-center rounded-full text-xs ${dateFor(day)===todayISO()?"bg-primary text-primary-foreground":""}`}>{day}</span><div className="mt-1 space-y-1">{entries.filter(e=>e.date===dateFor(day)).slice(0,2).map(e=><span key={e.id} className={`block truncate rounded px-1 py-0.5 text-[10px] ${tone(e.type)}`}>{e.title}</span>)}{entries.filter(e=>e.date===dateFor(day)).length>2&&<span className="text-[10px] text-muted-foreground">+ more</span>}</div></button>:<div key={index} className="min-h-20 border-b border-r bg-muted/30 sm:min-h-28"/>)}</div></div><aside><h3 className="mb-3 font-display text-lg">{formatDate(selected)}</h3>{selectedEntries.length?selectedEntries.map(e=><div key={e.id} className="mb-2 border-b pb-3"><span className={`rounded px-2 py-1 text-xs ${tone(e.type)}`}>{e.type}</span><p className="mt-2 text-sm font-medium">{e.title}</p><div className="mt-2 flex items-center gap-1">{e.programId&&<Link to="/programs/$programId" params={{programId:e.programId}} className="text-xs text-primary underline">Open program</Link>}{e.source&&<><Button size="icon" variant="ghost" aria-label={`Edit ${e.title}`} onClick={()=>show(e.source)}><Pencil className="size-3"/></Button><ConfirmationDialog trigger={<Button size="icon" variant="ghost" aria-label={`Delete ${e.title}`}><Trash2 className="size-3 text-destructive"/></Button>} title="Delete event?" description="This event will be removed from your calendar." onConfirm={()=>remove.mutate(e.id)}/></>}</div></div>):<p className="text-sm text-muted-foreground">No events on this day.</p>}<Button size="sm" variant="outline" className="mt-3" onClick={()=>show()}><Plus className="size-4"/> Add event</Button></aside></div>}
 <FormModal open={open} onOpenChange={setOpen} title={editing?"Edit event":"Add event"}><form onSubmit={submit} className="space-y-4"><Field label="Title" htmlFor="event-title" required><Input id="event-title" required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></Field><Field label="Date" htmlFor="event-date" required><Input id="event-date" type="date" required value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></Field><Field label="Type"><Select value={draft.event_type} onValueChange={v=>setDraft({...draft,event_type:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{EVENT_TYPES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Related program"><Select value={draft.program_id} onValueChange={v=>setDraft({...draft,program_id:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">None</SelectItem>{programs.map(p=><SelectItem key={p.id} value={p.id}>{p.university}</SelectItem>)}</SelectContent></Select></Field><Field label="Notes" htmlFor="event-notes"><Textarea id="event-notes" value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><label className="flex items-center gap-2 text-sm"><Checkbox checked={draft.completed} onCheckedChange={v=>setDraft({...draft,completed:v===true})}/> Completed</label><div className="flex justify-end"><Button type="submit" disabled={save.isPending}>Save event</Button></div></form></FormModal></AppShell>}
