import { createFileRoute } from "@tanstack/react-router";
import { Download, Eye, FileText, Pencil, Plus, Search, Trash2, Upload } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app/AppShell";
import { ConfirmationDialog } from "@/components/app/ConfirmationDialog";
import { EmptyState } from "@/components/app/EmptyState";
import { Field, FormModal } from "@/components/app/FormModal";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { DOCUMENT_STATUSES,DOCUMENT_TYPES } from "@/lib/constants";
import { useDocuments,useDeleteRow,useSaveRow,uploadDocumentFile,removeDocumentFile,documentFileUrl,type DocumentRow } from "@/lib/data";
import { formatDate } from "@/lib/format";
import { pageMeta } from "@/lib/page-meta";
import { StatusBadge } from "@/components/app/Badges";
export const Route=createFileRoute("/_authenticated/documents")({head:()=>pageMeta("Documents","Store and organize application documents and certificates."),component:DocumentsPage});
const EMPTY={name:"",document_type:"CV",version:"",status:"Draft",notes:""};
function DocumentsPage(){const {user}=Route.useRouteContext();const {data:documents=[],isLoading,isError}=useDocuments();const save=useSaveRow("documents","Document"),remove=useDeleteRow("documents","Document");const [query,setQuery]=useState(""),[type,setType]=useState("all"),[status,setStatus]=useState("all"),[open,setOpen]=useState(false),[draft,setDraft]=useState(EMPTY),[editing,setEditing]=useState<DocumentRow|null>(null),[file,setFile]=useState<File|null>(null);const fileRef=useRef<HTMLInputElement>(null);
 const filtered=documents.filter(d=>(d.name.toLowerCase().includes(query.toLowerCase())||d.document_type.toLowerCase().includes(query.toLowerCase()))&&(type==="all"||d.document_type===type)&&(status==="all"||d.status===status));
 function show(d?:DocumentRow){setEditing(d??null);setDraft(d?{name:d.name,document_type:d.document_type,version:d.version??"",status:d.status,notes:d.notes??""}:EMPTY);setFile(null);setOpen(true)}
 async function submit(e:React.FormEvent){e.preventDefault();if(!draft.name.trim())return;let path=editing?.file_url??null;try{if(file)path=await uploadDocumentFile(file);await save.mutateAsync({...draft,name:draft.name.trim(),version:draft.version||null,notes:draft.notes||null,file_url:path,...(editing?{id:editing.id}:{})});if(file&&editing?.file_url&&editing.file_url!==path)await removeDocumentFile(editing.file_url);setOpen(false)}catch(error){if(file&&path!==editing?.file_url)await removeDocumentFile(path);toast.error(error instanceof Error?error.message:"Could not save document")}}
 async function deleteDoc(d:DocumentRow){try{await remove.mutateAsync(d.id);await removeDocumentFile(d.file_url)}catch{}}
 async function openFile(d:DocumentRow,download=false){if(!d.file_url)return;try{const url=await documentFileUrl(d.file_url);const a=document.createElement("a");a.href=url;a.target="_blank";a.rel="noopener noreferrer";if(download)a.download=d.name;document.body.appendChild(a);a.click();a.remove()}catch{toast.error("Could not open file")}}
 return <AppShell title="Documents" subtitle="Your reusable application library" email={user.email} actions={<Button size="sm" onClick={()=>show()}><Plus className="size-4"/> Add document</Button>}><div className="mb-6 flex flex-wrap gap-2"><div className="relative min-w-48 flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input aria-label="Search documents" placeholder="Search documents…" className="pl-9" value={query} onChange={e=>setQuery(e.target.value)}/></div><Select value={type} onValueChange={setType}><SelectTrigger aria-label="Filter document type" className="w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All types</SelectItem>{DOCUMENT_TYPES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger aria-label="Filter document status" className="w-36"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{DOCUMENT_STATUSES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div>
 {isLoading?<p>Loading documents…</p>:isError?<p role="alert" className="text-destructive">Could not load documents.</p>:!filtered.length?<EmptyState title={documents.length?"No matching documents":"No documents yet"} description="Keep your application files in one place." action={!documents.length?<Button onClick={()=>show()}>Add document</Button>:undefined}/>:DOCUMENT_TYPES.filter(t=>filtered.some(d=>d.document_type===t)).map(t=><section key={t} className="mb-8"><h2 className="mb-3 text-lg">{t}</h2><div className="grid gap-3 lg:grid-cols-2">{filtered.filter(d=>d.document_type===t).map(d=><div key={d.id} className="flex min-w-0 items-start gap-3 rounded-lg border bg-surface p-4 shadow-[var(--shadow-card)]"><FileText className="mt-1 size-5 shrink-0 text-plum"/><div className="min-w-0 flex-1"><p className="truncate font-medium">{d.name}</p><p className="mt-1 text-xs text-muted-foreground">{d.version||"No version"} · {formatDate(d.created_at.slice(0,10))}</p><StatusBadge status={d.status} className="mt-2"/></div><div className="flex shrink-0 gap-0.5">{d.file_url&&<><Button variant="ghost" size="icon" title="Preview" aria-label={`Preview ${d.name}`} onClick={()=>void openFile(d)}><Eye className="size-4"/></Button><Button variant="ghost" size="icon" title="Download" aria-label={`Download ${d.name}`} onClick={()=>void openFile(d,true)}><Download className="size-4"/></Button></>}<Button variant="ghost" size="icon" title="Edit" aria-label={`Edit ${d.name}`} onClick={()=>show(d)}><Pencil className="size-4"/></Button><ConfirmationDialog trigger={<Button variant="ghost" size="icon" title="Delete" aria-label={`Delete ${d.name}`}><Trash2 className="size-4 text-destructive"/></Button>} title="Delete document?" description={`Delete “${d.name}” and its uploaded file? Linked requirements will lose their document reference.`} onConfirm={()=>void deleteDoc(d)}/></div></div>)}</div></section>)}
 <FormModal open={open} onOpenChange={setOpen} title={editing?"Edit document":"Add document"}><form onSubmit={submit} className="space-y-4"><Field label="Document name" htmlFor="doc-name" required><Input id="doc-name" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} required/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Type"><Select value={draft.document_type} onValueChange={v=>setDraft({...draft,document_type:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{DOCUMENT_TYPES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Status"><Select value={draft.status} onValueChange={v=>setDraft({...draft,status:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{DOCUMENT_STATUSES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field></div><Field label="Version" htmlFor="doc-version"><Input id="doc-version" value={draft.version} onChange={e=>setDraft({...draft,version:e.target.value})} placeholder="e.g. v2"/></Field><Field label="File" htmlFor="doc-file" hint="PDF or document, up to 25 MB"><Input ref={fileRef} id="doc-file" type="file" accept=".pdf,.doc,.docx,.txt,.jpg,.jpeg,.png" onChange={e=>setFile(e.target.files?.[0]??null)}/></Field>{editing?.file_url&&<p className="text-xs text-muted-foreground">Current file is kept unless you choose another.</p>}<Field label="Notes" htmlFor="doc-notes"><Textarea id="doc-notes" value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" disabled={save.isPending}><Upload className="size-4"/> {save.isPending?"Saving…":"Save document"}</Button></div></form></FormModal></AppShell>}
