import { createFileRoute } from "@tanstack/react-router";
import { Pencil,Plus,Trash2 } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/app/AppShell";
import { ConfirmationDialog } from "@/components/app/ConfirmationDialog";
import { EmptyState } from "@/components/app/EmptyState";
import { Field,FormModal } from "@/components/app/FormModal";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { TEST_TYPES } from "@/lib/constants";
import { useLanguageTests,useDocuments,useSaveRow,useDeleteRow,type LanguageTest } from "@/lib/data";
import { formatDate,formatMoney,todayISO } from "@/lib/format";
import { pageMeta } from "@/lib/page-meta";
export const Route=createFileRoute("/_authenticated/language-tests")({head:()=>pageMeta("Language Tests","Plan and track language test dates, scores, validity, and certificates."),component:LanguageTestsPage});
const NONE="none";const EMPTY={test_type:"IELTS Academic",test_date:"",expiry_date:"",score:"",listening:"",reading:"",writing:"",speaking:"",provider:"",price:"",currency:"USD",certificate_document_id:NONE,notes:""};
function LanguageTestsPage(){const {user}=Route.useRouteContext();const {data:tests=[],isLoading,isError}=useLanguageTests(),{data:documents=[]}=useDocuments();const save=useSaveRow("language_tests","Language test"),remove=useDeleteRow("language_tests","Language test");const [open,setOpen]=useState(false),[editing,setEditing]=useState<LanguageTest|null>(null),[draft,setDraft]=useState(EMPTY);
 function show(t?:LanguageTest){setEditing(t??null);setDraft(t?{test_type:t.test_type,test_date:t.test_date??"",expiry_date:t.expiry_date??"",score:t.score??"",listening:t.listening??"",reading:t.reading??"",writing:t.writing??"",speaking:t.speaking??"",provider:t.provider??"",price:t.price?.toString()??"",currency:t.currency??"USD",certificate_document_id:t.certificate_document_id??NONE,notes:t.notes??""}:EMPTY);setOpen(true)}
 async function submit(e:React.FormEvent){e.preventDefault();try{await save.mutateAsync({...draft,test_date:draft.test_date||null,expiry_date:draft.expiry_date||null,score:draft.score||null,listening:draft.listening||null,reading:draft.reading||null,writing:draft.writing||null,speaking:draft.speaking||null,provider:draft.provider||null,price:draft.price?Number(draft.price):null,certificate_document_id:draft.certificate_document_id===NONE?null:draft.certificate_document_id,notes:draft.notes||null,...(editing?{id:editing.id}:{})});setOpen(false)}catch{}}
 const planned=tests.filter(t=>!t.test_date||t.test_date>todayISO()),completed=tests.filter(t=>!!t.test_date&&t.test_date<=todayISO());
 const cards=(rows:LanguageTest[])=><div className="grid gap-4 lg:grid-cols-2">{rows.map(t=><article key={t.id} className="rounded-lg border bg-surface p-5 shadow-[var(--shadow-card)]"><div className="flex items-start justify-between gap-2"><div><h3 className="font-display text-lg font-semibold text-primary">{t.test_type}</h3><p className="text-sm text-muted-foreground">{t.provider||"Provider not set"}</p></div><div className="flex"><Button size="icon" variant="ghost" aria-label={`Edit ${t.test_type}`} onClick={()=>show(t)}><Pencil className="size-4"/></Button><ConfirmationDialog trigger={<Button size="icon" variant="ghost" aria-label={`Delete ${t.test_type}`}><Trash2 className="size-4 text-destructive"/></Button>} title="Delete language test?" description="This test record will be removed." onConfirm={()=>remove.mutate(t.id)}/></div></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><p><span className="block text-xs text-muted-foreground">Test date</span>{formatDate(t.test_date)}</p><p><span className="block text-xs text-muted-foreground">Expiry date</span>{formatDate(t.expiry_date)}</p><p><span className="block text-xs text-muted-foreground">Price</span>{formatMoney(t.price,t.currency)}</p><p><span className="block text-xs text-muted-foreground">Validity</span>{!t.test_date||t.test_date>todayISO()?"Planned":!t.expiry_date?"Expiry not set":t.expiry_date<todayISO()?"Expired":"Valid"}</p></div>{t.score&&<div className="mt-4 border-t pt-3"><p className="font-medium">Overall {t.score}</p><div className="mt-2 grid grid-cols-4 gap-1 text-xs">{[["Listening",t.listening],["Reading",t.reading],["Writing",t.writing],["Speaking",t.speaking]].map(([label,value])=><div key={label} className="rounded bg-secondary p-2"><span className="block text-muted-foreground">{label}</span><strong>{value||"—"}</strong></div>)}</div></div>}{t.certificate_document_id&&<p className="mt-3 text-xs text-plum">Certificate: {documents.find(d=>d.id===t.certificate_document_id)?.name||"Linked document"}</p>}{t.notes&&<p className="mt-3 text-sm text-muted-foreground">{t.notes}</p>}</article>)}</div>;
 return <AppShell title="Language Tests" subtitle="Scores, plans and certificates" email={user.email} actions={<Button size="sm" onClick={()=>show()}><Plus className="size-4"/> Add test</Button>}>{isLoading?<p>Loading tests…</p>:isError?<p role="alert" className="text-destructive">Could not load tests.</p>:tests.length===0?<EmptyState title="No language tests yet" description="Add a planned test or record a completed score." action={<Button onClick={()=>show()}>Add test</Button>}/>:<div className="space-y-9"><section><h2 className="mb-4 text-xl">Completed tests <span className="text-sm text-muted-foreground">{completed.length}</span></h2>{completed.length?cards(completed):<p className="text-sm text-muted-foreground">No completed tests yet.</p>}</section><section><h2 className="mb-4 text-xl">Planned tests <span className="text-sm text-muted-foreground">{planned.length}</span></h2>{planned.length?cards(planned):<p className="text-sm text-muted-foreground">Nothing planned yet.</p>}</section></div>}
 <FormModal open={open} onOpenChange={setOpen} title={editing?"Edit language test":"Add language test"}><form onSubmit={submit} className="space-y-4"><Field label="Test type"><Select value={draft.test_type} onValueChange={v=>setDraft({...draft,test_type:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{TEST_TYPES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><div className="grid grid-cols-2 gap-4">{[["Test date","test_date"],["Expiry date","expiry_date"]].map(([label,key])=><Field key={key} label={label} htmlFor={key}><Input id={key} type="date" value={draft[key as "test_date"|"expiry_date"]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></Field>)}</div><div className="grid grid-cols-2 gap-4">{[["Overall score","score"],["Listening","listening"],["Reading","reading"],["Writing","writing"],["Speaking","speaking"],["Provider","provider"],["Price","price"],["Currency","currency"]].map(([label,key])=><Field key={key} label={label} htmlFor={`test-${key}`}><Input id={`test-${key}`} type={key==="price"?"number":"text"} min={key==="price"?"0":undefined} value={draft[key as keyof typeof draft]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></Field>)}</div><Field label="Certificate document"><Select value={draft.certificate_document_id} onValueChange={v=>setDraft({...draft,certificate_document_id:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value={NONE}>None</SelectItem>{documents.map(d=><SelectItem key={d.id} value={d.id}>{d.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Notes" htmlFor="test-notes"><Textarea id="test-notes" value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" disabled={save.isPending}>Save test</Button></div></form></FormModal></AppShell>}
