import { createFileRoute,Link } from "@tanstack/react-router";
import { Mail,Pencil,Plus,Trash2 } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/app/AppShell";
import { DeadlineBadge,StatusBadge } from "@/components/app/Badges";
import { ConfirmationDialog } from "@/components/app/ConfirmationDialog";
import { EmptyState } from "@/components/app/EmptyState";
import { Field,FormModal } from "@/components/app/FormModal";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { RECOMMENDATION_STATUSES } from "@/lib/constants";
import { usePrograms,useRecommenders,useRecommendationRequests,useSaveRow,useDeleteRow,type Recommender,type RecommendationRequest } from "@/lib/data";
import { formatDate } from "@/lib/format";
import { pageMeta } from "@/lib/page-meta";
export const Route=createFileRoute("/_authenticated/recommendations")({head:()=>pageMeta("Recommendations","Manage recommenders and letter requests across your applications."),component:RecommendationsPage});
const EMPTY_PERSON={name:"",affiliation:"",position:"",email:"",notes:""}, EMPTY_REQUEST={program_id:"",recommender_id:"",deadline:"",requested_date:"",received_date:"",status:"Not Requested",notes:""};
function RecommendationsPage(){const {user}=Route.useRouteContext();const {data:programs=[]}=usePrograms(),{data:people=[],isLoading,isError}=useRecommenders(),{data:requests=[]}=useRecommendationRequests();const savePerson=useSaveRow("recommenders","Recommender"),saveRequest=useSaveRow("recommendation_requests","Request"),deletePerson=useDeleteRow("recommenders","Recommender"),deleteRequest=useDeleteRow("recommendation_requests","Request");const [personOpen,setPersonOpen]=useState(false),[requestOpen,setRequestOpen]=useState(false),[person,setPerson]=useState(EMPTY_PERSON),[request,setRequest]=useState(EMPTY_REQUEST),[personId,setPersonId]=useState<string|undefined>(),[requestId,setRequestId]=useState<string|undefined>();
 function editPerson(p?:Recommender){setPersonId(p?.id);setPerson(p?{name:p.name,affiliation:p.affiliation??"",position:p.position??"",email:p.email??"",notes:p.notes??""}:EMPTY_PERSON);setPersonOpen(true)}
 function editRequest(r?:RecommendationRequest){setRequestId(r?.id);setRequest(r?{program_id:r.program_id,recommender_id:r.recommender_id,deadline:r.deadline??"",requested_date:r.requested_date??"",received_date:r.received_date??"",status:r.status,notes:r.notes??""}:{...EMPTY_REQUEST,program_id:programs[0]?.id??"",recommender_id:people[0]?.id??""});setRequestOpen(true)}
 async function submitPerson(e:React.FormEvent){e.preventDefault();try{await savePerson.mutateAsync({...person,name:person.name.trim(),email:person.email||null,position:person.position||null,affiliation:person.affiliation||null,notes:person.notes||null,...(personId?{id:personId}:{})});setPersonOpen(false)}catch{}}
 async function submitRequest(e:React.FormEvent){e.preventDefault();if(!request.program_id||!request.recommender_id)return;try{await saveRequest.mutateAsync({...request,deadline:request.deadline||null,requested_date:request.requested_date||null,received_date:request.received_date||null,notes:request.notes||null,...(requestId?{id:requestId}:{})});setRequestOpen(false)}catch{}}
 return <AppShell title="Recommendations" subtitle="People and letters across your applications" email={user.email} actions={<Button size="sm" onClick={()=>editPerson()}><Plus className="size-4"/> Add recommender</Button>}><section className="mb-9"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl">Recommenders</h2></div>{isLoading?<p>Loading recommenders…</p>:isError?<p role="alert" className="text-destructive">Could not load recommenders.</p>:people.length?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{people.map(p=><article key={p.id} className="rounded-lg border bg-surface p-4 shadow-[var(--shadow-card)]"><div className="flex justify-between gap-2"><div><h3 className="font-display font-semibold text-primary">{p.name}</h3><p className="text-sm text-muted-foreground">{[p.position,p.affiliation].filter(Boolean).join(" · ")||"Affiliation not set"}</p></div><div className="flex"><Button size="icon" variant="ghost" aria-label={`Edit ${p.name}`} onClick={()=>editPerson(p)}><Pencil className="size-4"/></Button><ConfirmationDialog trigger={<Button size="icon" variant="ghost" aria-label={`Delete ${p.name}`}><Trash2 className="size-4 text-destructive"/></Button>} title="Delete recommender?" description="This person and their linked requests will be removed." onConfirm={()=>deletePerson.mutate(p.id)}/></div></div>{p.email&&<a href={`mailto:${p.email}`} className="mt-3 inline-flex items-center gap-1 text-xs text-primary"><Mail className="size-3"/>{p.email}</a>}<p className="mt-3 text-xs text-muted-foreground">{requests.filter(r=>r.recommender_id===p.id&&r.status!=="Received").length} active requests</p></article>)}</div>:<EmptyState title="No recommenders yet" description="Add someone who can write a letter for your applications." action={<Button onClick={()=>editPerson()}>Add recommender</Button>}/>}</section>
 <section><div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-xl">Letter requests</h2><Button variant="outline" size="sm" disabled={!people.length||!programs.length} onClick={()=>editRequest()}><Plus className="size-4"/> Add request</Button></div>{requests.length?<div className="space-y-3">{[...requests].sort((a,b)=>(a.deadline??"9999").localeCompare(b.deadline??"9999")).map(r=><article key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border bg-surface p-4"><div><Link to="/programs/$programId" params={{programId:r.program_id}} className="font-medium text-primary hover:underline">{programs.find(p=>p.id===r.program_id)?.university??"Program"}</Link><p className="text-sm text-muted-foreground">{people.find(p=>p.id===r.recommender_id)?.name??"Recommender"}</p><p className="mt-1 text-xs text-muted-foreground">Requested {formatDate(r.requested_date)} · Received {formatDate(r.received_date)} · Due {formatDate(r.deadline)}</p></div><div className="flex items-center gap-2"><StatusBadge status={r.status}/>{r.status!=="Received"&&r.deadline&&<DeadlineBadge date={r.deadline}/>}<Button size="icon" variant="ghost" aria-label="Edit request" onClick={()=>editRequest(r)}><Pencil className="size-4"/></Button><ConfirmationDialog trigger={<Button size="icon" variant="ghost" aria-label="Delete request"><Trash2 className="size-4 text-destructive"/></Button>} title="Delete request?" description="This recommendation request will be removed." onConfirm={()=>deleteRequest.mutate(r.id)}/></div></article>)}</div>:<EmptyState title="No letter requests yet" description="Link a recommender to a program to follow up on letters."/>}</section>
 <FormModal open={personOpen} onOpenChange={setPersonOpen} title={personId?"Edit recommender":"Add recommender"}><form onSubmit={submitPerson} className="space-y-4">{[["Name","name"],["Affiliation","affiliation"],["Position","position"],["Email","email"]].map(([label,key])=><Field key={key ?? ""} label={label} htmlFor={`person-${key ?? ""}`} required={key==="name"}><Input id={`person-${key ?? ""}`} type={key==="email"?"email":"text"} required={key==="name"} value={person[key as keyof typeof person]} onChange={e=>setPerson({...person,[key ?? ""]:e.target.value})}/></Field>)}<Field label="Notes" htmlFor="person-notes"><Textarea id="person-notes" value={person.notes} onChange={e=>setPerson({...person,notes:e.target.value})}/></Field><div className="flex justify-end"><Button type="submit" disabled={savePerson.isPending}>Save recommender</Button></div></form></FormModal>
 <FormModal open={requestOpen} onOpenChange={setRequestOpen} title={requestId?"Edit request":"Add request"}><form onSubmit={submitRequest} className="space-y-4"><Field label="Program"><Select value={request.program_id} onValueChange={v=>setRequest({...request,program_id:v})}><SelectTrigger><SelectValue placeholder="Choose a program"/></SelectTrigger><SelectContent>{programs.map(p=><SelectItem key={p.id} value={p.id}>{p.university} · {p.program_name}</SelectItem>)}</SelectContent></Select></Field><Field label="Recommender"><Select value={request.recommender_id} onValueChange={v=>setRequest({...request,recommender_id:v})}><SelectTrigger><SelectValue placeholder="Choose a person"/></SelectTrigger><SelectContent>{people.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Status"><Select value={request.status} onValueChange={v=>setRequest({...request,status:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{RECOMMENDATION_STATUSES.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></Field><div className="grid grid-cols-2 gap-4">{[["Deadline","deadline"],["Requested","requested_date"],["Received","received_date"]].map(([label,key])=><Field key={key ?? ""} label={label} htmlFor={`request-${key ?? ""}`}><Input id={`request-${key ?? ""}`} type="date" value={request[key as "deadline"|"requested_date"|"received_date"]} onChange={e=>setRequest({...request,[key ?? ""]:e.target.value})}/></Field>)}</div><Field label="Notes" htmlFor="request-notes"><Textarea id="request-notes" value={request.notes} onChange={e=>setRequest({...request,notes:e.target.value})}/></Field><div className="flex justify-end"><Button type="submit" disabled={saveRequest.isPending||!request.program_id||!request.recommender_id}>Save request</Button></div></form></FormModal></AppShell>}
